// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAu0fuB7uOTRHHeJUkBj9opBb4FTC-cFo',
    appId: '1:8706951967:web:9356685ae9dd48ca5a3e2a',
    messagingSenderId: '8706951967',
    projectId: 'petapp2-cdec9',
    authDomain: 'petapp2-cdec9.firebaseapp.com',
    storageBucket: 'petapp2-cdec9.appspot.com',
    measurementId: 'G-PXJB7LDK23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpAhzM9JE9lAoAUi0dm_ozjm1LRpNQjG8',
    appId: '1:8706951967:android:66efb1ecfa00da855a3e2a',
    messagingSenderId: '8706951967',
    projectId: 'petapp2-cdec9',
    storageBucket: 'petapp2-cdec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFcAysIMTUr5F5ynNBgLgltN56Ew7BEmA',
    appId: '1:8706951967:ios:efba5b29a72633855a3e2a',
    messagingSenderId: '8706951967',
    projectId: 'petapp2-cdec9',
    storageBucket: 'petapp2-cdec9.appspot.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAhaV2ObkUrwpTMgB5VjbAv3K9FRinhU8',
    appId: '1:805130321697:ios:efcb22cc797ef8a55d0860',
    messagingSenderId: '805130321697',
    projectId: 'petapp-d64b6',
    storageBucket: 'petapp-d64b6.appspot.com',
    iosBundleId: 'com.example.petApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbiyYqNWC--UxsBo7PacgfNLoN431FTXM',
    appId: '1:805130321697:web:62d80ec1296711655d0860',
    messagingSenderId: '805130321697',
    projectId: 'petapp-d64b6',
    authDomain: 'petapp-d64b6.firebaseapp.com',
    storageBucket: 'petapp-d64b6.appspot.com',
  );
}